version: '3.7'

services:
  database:
    container_name: youtube-video-database
    image: image-youtube-video-database
    build:
      context: ./src/database
      dockerfile: ./docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./src/database/docker/.database.env
    volumes:
      - type: volume
        source: youtube_video_database_data
        target: /var/lib/postgresql/pgdata
    ports:
      - target: 5432
        published: 5432
    networks:
      - youtube-video

  backend:
    container_name: youtube-video-backend
    image: image-youtube-video-backend
    build:
      context: ./src
      dockerfile: ./backend/docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./src/backend/docker/.backend.env
    volumes:
      - type: bind
        source: ./src/backend/youtube-video/src
        target: /youtube-video/backend/src
      - type: bind
        source: ./src/backend/youtube-video/config
        target: /youtube-video/backend/config
      - type: bind
        source: ./src/backend/youtube-video/coverage
        target: /youtube-video/backend/coverage
    ports:
      - target: 3100
        published: 3100
      - target: 9229
        published: 9229
    depends_on:
      - database
    networks:
      - youtube-video


  frontend:
    container_name: youtube-video-frontend
    image: image-youtube-video-frontend
    # stdin_open added due to a bug in reacts-scripts@^3.4.0
    # issue: https://github.com/git-insights/git-insights/issues/24
    stdin_open: true 
    build:
      context: ./src/frontend
      dockerfile: ./docker/Dockerfile
      args:
        - TZ=America/Sao_Paulo
    env_file:
      - ./src/frontend/docker/.frontend.env
    volumes:
      - type: bind
        source: ./src/frontend/youtube-video/public
        target: /youtube-video/frontend/public
      - type: bind
        source: ./src/frontend/youtube-video/src
        target: /youtube-video/frontend/src
      - type: bind
        source: ./src/frontend/youtube-video/coverage
        target: /youtube-video/frontend/coverage
    ports:
      - target: 3000
        published: 3000
    depends_on:
      - backend
    networks:
      - youtube-video

volumes:
  youtube_video_database_data:

networks:
  youtube-video
